# -----------------------------------------------
#  7. Data Visualization:
#  Objective: Visualize the word frequencies
#  using a visualization library.
# 
#  Tools/Resources: Examples of visualization 
#  libraries D3, Plotly, and Chart.JS.
#     D3, https://d3js.org/
#     Plotly, https://plotly.com/
#     Chart.JS, https://www.chartjs.org/
#     Google Charts, https://developers.google.com/chart/
# -----------------------------------------------

from __future__ import annotations

import csv
from html import escape

from catalog_utils import BASE_DIR, OUTPUT_DIR, ensure_directories, write_text

SOURCE = "ne"


def read_word_freq(top_n: int = 30) -> list[tuple[str, int]]:
    in_file = OUTPUT_DIR / f"{SOURCE}_title_freq.csv"
    if not in_file.exists():
        raise SystemExit(f"Missing {in_file}. Run 06_frequency.py first.")

    rows: list[tuple[str, int]] = []
    with in_file.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append((row["word"], int(row["count"])))
    return rows[:top_n]


def render_freq_chart(rows: list[tuple[str, int]]) -> str:
    if not rows:
        return "<p>No data</p>"

    max_val = max(v for _, v in rows) or 1
    bars = []
    for word, count in rows:
        width = int((count / max_val) * 100)
        bars.append(
            f"<div class='bar-row'><span class='label'>{escape(word)}</span>"
            f"<div class='bar-wrap'><div class='bar' style='width:{width}%'></div></div>"
            f"<span class='value'>{count}</span></div>"
        )

    return "\n".join(bars)


def build_html(rows: list[tuple[str, int]]) -> str:
    return f"""<!doctype html>
<html lang='en'>
<head>
  <meta charset='utf-8' />
  <meta name='viewport' content='width=device-width, initial-scale=1' />
  <title>NE Title Frequency</title>
  <style>
    body {{ margin:0; font-family: 'Trebuchet MS', Verdana, sans-serif; background:#f7f4ed; color:#1f2933; }}
    .wrap {{ max-width:900px; margin:0 auto; padding:24px; }}
    .card {{ background:#fffdf8; border:1px solid #dfd8c8; border-radius:12px; padding:14px; }}
    h1 {{ margin:0 0 8px; font-size:26px; }}
    .sub {{ color:#5f6c72; margin:0 0 14px; }}
    .bar-row {{ display:grid; grid-template-columns: 170px 1fr 50px; gap:8px; align-items:center; margin:6px 0; }}
    .label {{ font-size:13px; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }}
    .bar-wrap {{ height:10px; background:#ece4d5; border-radius:999px; overflow:hidden; }}
    .bar {{ height:100%; border-radius:999px; background:#2a6f8f; }}
    .value {{ text-align:right; font-size:12px; color:#5f6c72; }}
    .note {{ font-size:12px; color:#5f6c72; margin-top:10px; line-height:1.4; }}
  </style>
</head>
<body>
  <div class='wrap'>
    <h1>Top Words in Course Titles (NE)</h1>
    <p class='sub'>Generated by `07_visualization.py` from `06_frequency.py` output.</p>
    <section class='card'>
      {render_freq_chart(rows)}
      <div class='note'>Note: top tokens can include subject abbreviations (e.g., cs, eece), not only thematic keywords.</div>
    </section>
  </div>
</body>
</html>
"""


def main() -> None:
    ensure_directories()
    rows = read_word_freq(top_n=30)
    html = build_html(rows)

    runtime_file = OUTPUT_DIR / f"{SOURCE}_freq_top30.html"

    write_text(runtime_file, html)

    print(f"Saved frequency visualization -> {runtime_file}")


if __name__ == "__main__":
    main()
